SawLuzProj/Models/Restaurantes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SawLuzProj.Models
{
    public class Restaurantes
    {
        [Key]
        public int RestauranteId { get; set; }

        public string NomeRestaurante { get; set; }

        public ICollection<Pratos> Pratos { get; set; }
    }

}

SawLuzProj/Controllers/RestaurantesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SawLuzProj.Models;
using SawLuzProj.Context;
using System.Threading.Tasks;

namespace SawLuzProj.Controllers
{
    public class RestaurantesController : Controller
    {
        private RestauranteContext db = new RestauranteContext();

        //
        // GET: /Restaurantes/

        public ActionResult Index(string filtro)
        {
            

            if (!String.IsNullOrEmpty(filtro))
            {
                return View(db.Restaurantes.Where(s => s.NomeRestaurante.Contains(filtro)));
            }
            else { return View(db.Restaurantes.ToList()); }
        }

        //
        // GET: /Restaurantes/Details/5

        public ActionResult Details(int id = 0)
        {
            Restaurantes restaurantes = db.Restaurantes.Find(id);
            if (restaurantes == null)
            {
                return HttpNotFound();
            }
            return View(restaurantes);
        }

        //
        // GET: /Restaurantes/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Restaurantes/Create

        [HttpPost]
        public ActionResult Create(Restaurantes restaurantes)
        {
            if (ModelState.IsValid)
            {
                db.Restaurantes.Add(restaurantes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(restaurantes);
        }

        //
        // GET: /Restaurantes/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Restaurantes restaurantes = db.Restaurantes.Find(id);
            if (restaurantes == null)
            {
                return HttpNotFound();
            }
            return View(restaurantes);
        }

        //
        // POST: /Restaurantes/Edit/5

        [HttpPost]
        public ActionResult Edit(Restaurantes restaurantes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(restaurantes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(restaurantes);
        }

        //
        // GET: /Restaurantes/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Restaurantes restaurantes = db.Restaurantes.Find(id);
            if (restaurantes == null)
            {
                return HttpNotFound();
            }
            return View(restaurantes);
        }

        //
        // POST: /Restaurantes/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            foreach (Pratos prato in db.Pratos)
            {
                if (prato.RestauranteId == id)
                {
                    db.Pratos.Remove(prato);
                }
            }

            Restaurantes restaurantes = db.Restaurantes.Find(id);
            db.Restaurantes.Remove(restaurantes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult Search(string searchString)
        {
            return View(db.Restaurantes.Where(x => x.NomeRestaurante.Contains(searchString)).OrderBy(x => x.NomeRestaurante));
        }

    }
}

SawLuzProj/Views/Restaurantes/Create.cshtml
@model SawLuzProj.Models.Restaurantes

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

<h2>Cadastro Restaurantes</h2>
<br />
<br />
<fieldset style="border:1px solid black; margin-bottom:10px">
    <legend style="display:block">Dados</legend>
    <div style="margin-left:10px;margin-top:10px">
        <div class="editor-label">
            @Html.Label("Nome do Restaurante")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NomeRestaurante)
            @Html.ValidationMessageFor(model => model.NomeRestaurante)
        </div>

        <p>
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "buttonCancel" })
            <input type="submit" value="Salvar" class="buttonCreate" />
        </p>

        
    </div>
</fieldset>

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SawLuzProj/Views/Restaurantes/Delete.cshtml
@model SawLuzProj.Models.Restaurantes

@{
    ViewBag.Title = "Delete";
}
<h2>Deletar Restaurantes</h2>
<br />
<h3>Tem Certeza que deseja excluir esse restaurante?</h3>
<br />
<fieldset style="border:1px solid black; margin-bottom:10px">
    <legend style="display:block">Dados</legend>
    <div style="margin-left:10px;margin-top:10px">
        <div class="editor-label">
            <div class="display-label" style="font-weight:bold">
                 @Html.DisplayName("Nome do Restaurante")
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.NomeRestaurante)
            </div>  

            <p>
                @using (Html.BeginForm()) {
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "buttonCancel" })
                    <input type="submit" value="Excluir" class="buttonSave" />
                }
            </p>
        </div>
</fieldset>

SawLuzProj/Views/Restaurantes/Details.cshtml
@model SawLuzProj.Models.Restaurantes

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Restaurantes</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NomeRestaurante)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NomeRestaurante)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.RestauranteId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SawLuzProj/Views/Restaurantes/Edit.cshtml
@model SawLuzProj.Models.Restaurantes

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    
<h2>Editar Restaurantes</h2>
<br />
<br />
<fieldset style="border:1px solid black; margin-bottom:10px">
    <legend style="display:block">Dados</legend>
    <div style="margin-left:10px;margin-top:10px">
        @Html.HiddenFor(model => model.RestauranteId)

        <div class="editor-label" style="font-weight:bold">
            @Html.Label("Nome do Restaurante")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NomeRestaurante)
            @Html.ValidationMessageFor(model => model.NomeRestaurante)
        </div>

        <p>
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "buttonCancel" })
            <input type="submit" value="Save" class="buttonSave" />
        </p>
    </div>
</fieldset>        
   
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SawLuzProj/Views/Restaurantes/Index.cshtml
@model IEnumerable<SawLuzProj.Models.Restaurantes>

@{
    ViewBag.Title = "Index";
}

<h2>Restaurantes</h2>
<br />
<br />
<fieldset style="border:1px solid black; margin-bottom:10px">
    <legend style="display:block">Filtros</legend>
    <div style="margin-left:10px;margin-top:10px">
        <form asp-controller="Restaurantes" asp-action="Index">
            <p>
                <span style="margin-left:10px">Nome</span> <br /><input style="margin-left:10px" type="text" name="filtro" value="@ViewData["filtro"]" />
                <br /><br />
                <input type="submit" value="Pesquisar" class="buttonSearch" />
                @Html.ActionLink("Cadastrar novo restaurante", "Create", null, new { @class = "buttonCreate" })
            </p>
        </form>
        
    </div>
    
</fieldset>
<br />
<br />
        <table class="table_Color">
            <tr style="background:#b9b7b7">
                <th></th>
                <th></th>
                <th>
                    @Html.DisplayName("Restaurante")
                </th>
            </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id=item.RestauranteId }, new { @class = "imgDelete"})
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.RestauranteId }, new { @class = "imgEdit"})          
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeRestaurante)
                </td>
        
            </tr>
        }

        </table>
<br />
<br />
<br />
<br />